# Generated by Django 4.2.11 on 2024-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('rpg_status', models.IntegerField(choices=[(1, 'Booking'), (2, 'Cancellation')])),
                ('room_id', models.IntegerField()),
                ('night_of_stay', models.DateField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
